services:
  db:
    image: postgres:17
    container_name: notes-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: notes_db
      POSTGRES_USER: transcler
      POSTGRES_PASSWORD: ILHAM2705I
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: notes-app
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "127.0.0.1:3000:3000"

volumes:
  postgres_data:


